### ISSUE TITLE
Redundant checkout action in the integration.yml workflow

### ISSUE THREAD

**Issue by sahil-sagwekar2652** [kworkflow/kworkflow#1075]
The first job in the `.github: workflow: integration_tests.yml` file seems redundant as we are also using the same checkout action in the second job.
Apologies if I'm missing some point.

```yaml
name: Integration tests
on:
  ...

jobs:
  ...

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
  
  ...
```
